### ISSUE TITLE
Segfaults after a few nginx reloads

### ISSUE THREAD

**Issue by carolinebeauchamp** [fdintino/nginx-upload-module#58]
We've been getting segfaults for our upload urls after reloading the server a few times - this is reproducible. I've installed from chris-lea's ubuntu ppa (nginx-extras, version 1.5.10-1chl1~precise1) which is a pretty up to date version of the upload module (only missing the last commit). After a few reloads, nginx will start to segfault on one of the two upload urls configured (generally only one of them).

I've been looking through the core file with gdb and it appears to be segfaulting in: (from src/http/ngx_http_script.c)

```
void
ngx_http_script_flush_complex_value(ngx_http_request_t *r,
    ngx_http_complex_value_t *val)
{
    ngx_uint_t *index;

    index = val->flushes;

    if (index) {
        while (*index != (ngx_uint_t) -1) {

            if (r->variables[*index].no_cacheable) {
                r->variables[*index].valid = 0;
                r->variables[*index].not_found = 0;
            }

            index++;
        }
    }
}
```

index (val->flushes) doesn't look like a pointer value - it is 1 in the core that I have - but then I'm not familiar enough with the nginx code to know exactly what's happening.

Going to do more investigation cutting down on modules loaded and config used etc, but in the meantime, would someone have some clues as to what's happening?

Thanks!

Chris

I've got the following information:

Segfault:

syslog:

```
Feb 19 16:44:35 cbtsof7 kernel: [1392441.036355] nginx[20783]: segfault at 1 ip 000000000048bba9 sp 00007fff0824fe38 error 4 in nginx[400000+2d8000]
```

error.log:

```
2014/02/19 16:44:35 [alert] 17040#0: worker process 20783 exited on signal 11 (core dumped)
```

Backtrace:

```
(gdb) bt
#0  ngx_http_script_flush_complex_value (r=0xca55a0, val=0xdc2728) at src/http/ngx_http_script.c:44
#1  0x000000000048bc15 in ngx_http_complex_value (r=0xca55a0, val=0xdc2728, value=0x7fff0824ff00) at src/http/ngx_http_script.c:71
#2  0x00000000004f778b in ngx_http_upload_eval_state_path (r=0xca55a0) at /build/buildd/nginx-1.5.10/debian/modules/nginx-upload-module-2.2/ngx_http_upload_module.c:975
#3  ngx_http_upload_handler (r=0xca55a0) at /build/buildd/nginx-1.5.10/debian/modules/nginx-upload-module-2.2/ngx_http_upload_module.c:865
#4  ngx_http_upload_handler (r=0xca55a0) at /build/buildd/nginx-1.5.10/debian/modules/nginx-upload-module-2.2/ngx_http_upload_module.c:771
#5  0x0000000000478a02 in ngx_http_core_content_phase (r=0xca55a0, ph=0xdc4050) at src/http/ngx_http_core_module.c:1410
#6  0x00000000004732f5 in ngx_http_core_run_phases (r=0xca55a0) at src/http/ngx_http_core_module.c:888
#7  0x000000000047f2a2 in ngx_http_process_request (r=0xca55a0) at src/http/ngx_http_request.c:1842
#8  0x00000000004801e6 in ngx_http_process_request_line (rev=0xf5ab98) at src/http/ngx_http_request.c:954
#9  0x0000000000480842 in ngx_http_ssl_handshake_handler (c=0x1165b48) at src/http/ngx_http_request.c:743
#10 ngx_http_ssl_handshake_handler (c=0x1165b48) at src/http/ngx_http_request.c:694
#11 0x0000000000460098 in ngx_event_process_posted (cycle=0xc630a0, posted=0x908f08) at src/event/ngx_event_posted.c:40
#12 0x0000000000466f99 in ngx_worker_process_cycle (cycle=0xc630a0, data=<optimised out>) at src/os/unix/ngx_process_cycle.c:816
#13 0x0000000000465955 in ngx_spawn_process (cycle=0xc630a0, proc=0x466ee0 <ngx_worker_process_cycle>, data=0x0, name=0x62fd47 "worker process", respawn=-4) at src/os/unix/ngx_process.c:198
#14 0x00000000004671d4 in ngx_start_worker_processes (cycle=0xc630a0, n=4, type=-4) at src/os/unix/ngx_process_cycle.c:364
#15 0x000000000046809a in ngx_master_process_cycle (cycle=0xc630a0) at src/os/unix/ngx_process_cycle.c:249
#16 0x000000000044636d in main (argc=<optimised out>, argv=<optimised out>) at src/core/nginx.c:407 
```

version:

```
nginx version: nginx/1.5.10
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-log-path=/var/log/nginx/access.log --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --lock-path=/var/lock/nginx.lock --pid-path=/var/run/nginx.pid --with-pcre-jit --with-debug --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_geoip_module --with-http_gzip_static_module --with-http_image_filter_module --with-http_mp4_module --with-http_perl_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_stub_status_module --with-http_ssl_module --with-http_sub_module --with-http_xslt_module --with-http_spdy_module --with-ipv6 --with-mail --with-mail_ssl_module --with-openssl=/build/buildd/nginx-1.5.10/debian/openssl-1.0.1f --add-module=/build/buildd/nginx-1.5.10/debian/modules/nginx-auth-pam --add-module=/build/buildd/nginx-1.5.10/debian/modules/headers-more-nginx-module --add-module=/build/buildd/nginx-1.5.10/debian/modules/nginx-development-kit --add-module=/build/buildd/nginx-1.5.10/debian/modules/nginx-echo --add-module=/build/buildd/nginx-1.5.10/debian/modules/nginx-http-push --add-module=/build/buildd/nginx-1.5.10/debian/modules/nginx-upload-progress --add-module=/build/buildd/nginx-1.5.10/debian/modules/nginx-upload-module-2.2 --add-module=/build/buildd/nginx-1.5.10/debian/modules/nginx-upstream-fair --add-module=/build/buildd/nginx-1.5.10/debian/modules/nginx-dav-ext-module --add-module=/build/buildd/nginx-1.5.10/debian/modules/nginx-cache-purge
```

config:

Our config is long and convoluted - I'll work on a cut down test case and post that here. In the meantime, here are the appropriate bits for the upload server:
nginx.conf

```
user vault;
worker_processes  4;
worker_rlimit_core  500M;
working_directory   /data/nginxcores;

error_log  /var/log/nginx/error.log;
pid        /var/run/nginx.pid;

events {
  worker_connections  2048;
}

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;

  types_hash_max_size 2048;
  types_hash_bucket_size 64;

  access_log    /var/log/nginx/access.log;
  log_format  fluentd '"hostname":"$hostname","server":"$server_name", "method":"$request_method", "remoteaddr":"$remote_addr", "uri":"$request_uri", "status":$status, "referer":"$http_referer", "useragent":"$http_user_agent","reqtime":$request_time, "bytes":$bytes_sent, "virtualhost":"$http_host", "msec":$msec';
  access_log  /var/log/nginx/fluent.log fluentd;

  sendfile on;
  tcp_nopush on;
  tcp_nodelay on;

  keepalive_timeout  0;
  client_body_timeout 300;
  client_header_timeout 300;
  send_timeout 300;

  proxy_read_timeout 300;

  gzip  off;

  server_names_hash_bucket_size 64;
  variables_hash_max_size 1024;

  include /etc/nginx/conf.d/*.conf;
  include /etc/nginx/sites-enabled/*;
}
```

virtual host config (there are 2 of these, exactly the same, except for different URIs and upload_stores):

```
....
   # Upload form should be submitted to this location
   location = /upload/1 {

        # Pass altered request body to this location
        upload_pass   @test;

        # Store files to this directory
        # The directory is hashed, subdirectories 0 1 2 3 4 5 6 7 8 9 should exist
        upload_store /mnt1/assets/tmp 1;

        # Allow uploaded files to be read only by user
        upload_store_access user:rw group:rw all:rw;
#       upload_store_access 066

        # Set specified fields in request body
        upload_set_form_field $upload_field_name.name "$upload_file_name";
        upload_set_form_field $upload_field_name.content_type "$upload_content_type";
        upload_set_form_field $upload_field_name.path "$upload_tmp_path";

        # Inform backend about hash and size of a file
        upload_aggregate_form_field "$upload_field_name.sha1" "$upload_file_sha1";
        upload_aggregate_form_field "$upload_field_name.size" "$upload_file_size";

        upload_pass_form_field "^submit$|^description$|^token$|^qqfile$|^file1$|^chunk$|^chunks$|^chunk_base64_sha_hash$|^storage_path$|^storage_unit$|^server$";

        if ($request_method = 'OPTIONS') {
           add_header Access-Control-Allow-Origin '*';
           add_header Access-Control-Allow-Methods 'POST, OPTIONS';
           add_header Access-Control-Max-Age '1728000';
           add_header Content-Type: 'text/plain; charset=UTF-8';
           add_header Access-Control-Allow-Headers 'X-CSRF-Token';
           return 200;
        }

        # FILE UPLOADS
        if ($request_method = 'POST') {
           add_header Access-Control-Allow-Origin: '*';
        }

        upload_cleanup 400 404 499 500-505;
    }

    location @test {
        proxy_pass   http://127.0.0.1:8090;
    }

.....

```

**Comment by khavishbhundoo** [comment]
@fdintino  This issue can also be closed
